orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register, name='register'),
    path("enter", views.enter, name='enter'),
    path("exit", views.exit, name='exit'),
    path("pizza/<id>/<item>", views.process_order, name='process_order'),
    path("cart/<order_id>", views.process_cart, name='process_cart'),
    path("display_orders", views.display_orders, name='display_orders'),
    path("clear_cart", views.clear_cart, name='clear_cart')


]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
]

orders/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Size(models.Model):
    description = models.CharField(max_length=5)

    def __unicode__(self):
	    return self.description

class Topping(models.Model):
    description = models.CharField(max_length=24)

    def __unicode__(self):
	    return self.description

class Option(models.Model):
    description = models.CharField(max_length=24)
    number_of_topings = models.IntegerField(default=0)

    def __unicode__(self):
        return self.description

class Pizza_Type(models.Model):
    description = models.CharField(max_length=24)

    def __unicode__(self):
        return self.description

class Dinner_Plate_Type(models.Model):
    description = models.CharField(max_length=24)

    def __unicode__(self):
        return self.description

class Pizza(models.Model):

    type = models.ForeignKey(Pizza_Type, null=True, on_delete=models.SET_NULL)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    size = models.ForeignKey(Size, null=True, on_delete=models.SET_NULL)
    option = models.ForeignKey(Option, null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return str(self.id)

class Pasta(models.Model):

    description = models.CharField(max_length=24)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)

    def __unicode__(self):
        return str(self.id)

class Salad(models.Model):

    description = models.CharField(max_length=24)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)

    def __unicode__(self):
        return str(self.id)

class Item(models.Model):

    type = models.ForeignKey(Dinner_Plate_Type, null=True, on_delete=models.SET_NULL)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    size = models.ForeignKey(Size, null=False, on_delete=models.PROTECT)

    def __unicode__(self):
        return str(self.id)


class Pizza_Assembly (models.Model):

    pizza = models.ForeignKey(Pizza, null=False, on_delete=models.PROTECT)
    toppings = models.ManyToManyField(Topping)

    def __unicode__(self):
        return str(self.id)

class Order(models.Model):

    customer = models.ForeignKey(User, null=False, on_delete=models.PROTECT)
    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)
    pizzas_assemblies = models.ManyToManyField(Pizza_Assembly)
    dinner_plates = models.ManyToManyField(Item)
    salads = models.ManyToManyField(Salad)
    pastas = models.ManyToManyField(Pasta)
    is_complete = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)
    total = models.DecimalField(max_digits=6,decimal_places=2,default=0.00)

    def __unicode__(self):
        return str(self.id)

orders/forms.py
from django import forms
from .models import Topping
from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(required=True, widget=forms.TextInput())
    last_name = forms.CharField(required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True,widget=forms.TextInput())

    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'email']

class LoginForm(forms.Form):


    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ['username', 'password']


class ToppingsForm(forms.ModelForm):

    all_toppings = [(topping.description) for topping in Topping.objects.all()]

    toppings = forms.MultipleChoiceField(choices=all_toppings, widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Topping
        fields = ['description']

orders/views.py
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm, LoginForm, ToppingsForm
from .models import Topping, Pizza_Assembly, Pizza_Type, Pizza, Order, Size, Option, Salad, Pasta, Item, Dinner_Plate_Type
from django.shortcuts import render
from django.shortcuts import redirect
from decimal import Decimal
from django.contrib import messages

def index(request):


    # Get all collections needed to display menu
    pizzas = Pizza.objects.all()
    toppings = Topping.objects.all()
    sizes = Size.objects.all()
    types = Pizza_Type.objects.all()
    options = Option.objects.all()
    salads = Salad.objects.all()
    pastas = Pasta.objects.all()
    items = Item.objects.all()
    plates = Dinner_Plate_Type.objects.all()

    # Pass all collections to the index page
    return render(request, 'index.html', {'pizzas': pizzas, 'toppings': toppings, 'sizes': sizes, 'types': types,
                                          'options': options, 'salads': salads, 'pastas': pastas, 'items': items,
                                          'plates': plates })

def exit(request):

    # Logout current user and redirect to the menu
    logout(request)
    return redirect("/")

def enter(request):

    # Create form from the request
    form = LoginForm(request.POST or None)

    # If form is valid extract data
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        # Try to authenticate the user
        user = authenticate(username=username, password=password)

        # If user exists but not in the active state return an error
        # If user does not exist return and error
        # Otherwise login the user
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect("/")
            else:
                messages.error(request, "User is not active !!!")
        else:
            messages.error(request, "Incorrect user login !!!")

    return render(request, 'login.html', {'form': form})


def register(request):

    # Create form from the request
    form = RegisterForm(request.POST or None)

    # If form is valid extract data and save the user in the database
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)

        # If user is not found return all the error encountered during registration
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            messages.error(request, form.errors)
    else:
        messages.error(request, form.errors)

    return render(request, 'register.html', {'form': form})

def process_order(request, id, item):

    # If user is not authenticated redirect them to the login page
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        if request.method == "POST":

            # Retrieve and order from the data base that has not been completed. It is impossible to have more than
            # one uncompleted order for the same user
            order = Order.objects.filter(customer=request.user.id, is_paid=False).first()

            # If order does not exist it must be new order
            if order is None:
                order = Order()
                order.customer = request.user
                order.is_complete = False
                order.is_paid = False
                order.save()

            # Check to see what is being ordered
            if item == "pizza":

                pizza = Pizza.objects.get(pk=id)
                toppings = Topping.objects.filter(description__in=request.POST.getlist('toppings'))

                if pizza.option.number_of_topings != len(request.POST.getlist('toppings')):
                    form = ToppingsForm()
                    return render(request, 'cart.html', {'error': 'Number of selected topics does not match choice of Pizza',
                                                         'pizza': pizza, 'form': form })

                # Looks like user is ordering pizza
                pizza_assembly = Pizza_Assembly()
                pizza_assembly.pizza = pizza
                pizza_assembly.save()
                pizza_assembly.toppings.add(*list(toppings))
                pizza_assembly.save()


                order.pizzas_assemblies.add(pizza_assembly)
                order.total = Decimal(order.total) + pizza.price
                order.save()

            elif item == "salad":

                # Looks like user is ordering salad
                salad = Salad.objects.get(pk=id)
                order.salads.add(salad)
                order.total = Decimal(order.total) + salad.price
                order.save()

            elif item == "pasta":

                # Looks like user is ordering pasta
                pasta = Pasta.objects.get(pk=id)
                order.pastas.add(pasta)
                order.total = Decimal(order.total) + pasta.price
                order.save()

            elif item == "plate":

                # Looks like user is ordering dinner plate
                plate = Item.objects.get(pk=id)
                order.dinner_plates.add(plate)
                order.total = Decimal(order.total) + plate.price
                order.save()

            return render(request, 'order.html', {'order': order})

        elif request.method == "GET":

            # if user is ordering pizza display toppings sellection form
            if item == "pizza":
                form = ToppingsForm()
                pizza = Pizza.objects.get(pk=id)

                return render(request, 'cart.html', {'pizza': pizza, 'form': form})

            elif item == "salad":
                salad = Salad.objects.get(pk=id)

                return render(request, 'cart.html', {'salad': salad })

            elif item == "pasta":
                pasta = Pasta.objects.get(pk=id)

                return render(request, 'cart.html', {'pasta': pasta })

            elif item == "plate":
                plate = Item.objects.get(pk=id)

                return render(request, 'cart.html', {'plate': plate })

            else:
                return redirect("/")

def process_cart(request, order_id):

    # If user is not authenticated redirect them to the login page
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        if request.method == "POST":

            # Looks like user is trying to pay for the order
            order = Order.objects.get(pk=order_id)
            order.is_paid = True
            order.save()

            return redirect("/")

        elif request.method == "GET":

            # Looks like user is trying to see what's in the cart
            if order_id is not '0':
                # If order id is passed fetch it, otherwise get first order for the user that has not been paid
                order = Order.objects.get(pk=order_id)
            else:
                order = Order.objects.filter(customer=request.user.id, is_paid=False).first()

            if order is None:
                return render(request, 'order.html', {'error': 'There are currently no active orders in the cart !!!'})
            else:
                return render(request, 'order.html', {'order': order})

def clear_cart(request):

    # If user is not authenticated redirect them to the login page
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        if request.method == "POST":

            # Looks like user is trying to start over. Let's delete first incomplete order
            order = Order.objects.filter(customer=request.user.id, is_paid=False).first()
            if order is not None:
                order.delete()

            return redirect("/")


def display_orders(request):

    # If user is not authenticated redirect them to the login page
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:

        # Fetch all the paid orders for a given user
        orders = Order.objects.filter(customer=request.user.id, is_paid=True).all()

        if len(orders) == 0:
            return render(request, 'order_list.html',
                          {'error': 'You have no orders !!!'})
        else:
            return render(request, 'order_list.html', {'orders': orders})

orders/templates/cart.html
{% extends 'visitor.html' %}
{% block title %}Cart{% endblock %}
{% block cart_active %}active{% endblock %}

{% block body %}
<div class="container-fluid pizza-container">
    <div class="row">
        <div class="col-sm-8 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if pizza %}
                        <h4>You Have Chosen</h4>
                        <ul>
                            <li><b>Pizza:</b> {{ pizza.type.description }}</li>
                            <li><b>With:</b> {{ pizza.option.description }}</li>
                            <li><b>Size:</b> {{ pizza.size.description }}</li>
                            <li><b>Price:</b> {{ pizza.price }}</li>
                        </ul>
                    {% elif salad %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <h4>You Have Chosen</h4>
                                <ul>
                                    <li><b>Salad:</b> {{ salad.description }}</li>
                                    <li><b>Price:</b> {{ salad.price }}</li>
                                </ul>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    {% elif pasta %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <h4>You Have Chosen</h4>
                                <ul>
                                    <li><b>Pasta:</b> {{ pasta.description }}</li>
                                    <li><b>Price:</b> {{ pasta.price }}</li>
                                </ul>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    {% elif plate %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <h4>You Have Chosen</h4>
                                <ul>
                                    <li><b>Plate:</b> {{ plate.type.description }}</li>
                                    <li><b>Plate:</b> {{ plate.size.description }}</li>
                                    <li><b>Price:</b> {{ plate.price }}</li>
                                </ul>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    {% endif %}
                </div>
                <div class="panel-footer">
                    <a href="{% url 'orders:index' %}">Back to Menu</a>
                </div>
            </div>
        </div>
        {% if pizza %}
        <div class="col-sm-4 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error %}
                        <p><strong>{{ error }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if pizza.option.number_of_topings != 0%}
                            <h4>Please Select Pizza Toppings</h4>
                            <ul>
                                {% for topping in form.toppings.field.choices %}
                                    <li>
                                        <input type="checkbox" name="toppings" value="{{topping}}"/> {{ topping }}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                           <h4>No Toppings to Select</h4>
                        {% endif %}
                        <div class="form-group">
                            <div class='wrapper text-center'>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

orders/templates/order.html
{% extends 'visitor.html' %}
{% block title %}Cart{% endblock %}
{% block cart_active %}active{% endblock %}

{% block body %}
<div class="container-fluid pizza-container">
    {% if order %}
        <div class="row">
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" action="{% url 'orders:process_cart' order.id %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                                <h4>Please Review Your Order</h4>
                                <ul>
                                    <li>Order ID: {{ order.id }}</li>
                                    <li>Total: {{ order.total }}</li>
                                </ul>
                                <div class="form-group">
                                    <div class='wrapper text-center'>
                                        <button type="submit" class="btn btn-success">Purchase</button>
                                    </div>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error %}
                        <p><strong>{{ error }}</strong></p>
                    {% endif %}
                    {% if order %}
                        {% for pizza_assembly in order.pizzas_assemblies.all %}
                            <div class="card card-cascade wider">
                                <div class="card-body text-center">
                                    <div class="col-xs-6 col-md-4">
                                            <img src="https://www.cicis.com/media/1176/pizza_trad_pepperonibeef.png" alt="Card image" class="img-thumbnail">
                                            <p class="card-title"><b>{{ pizza_assembly.pizza.type.description }}</b> </p>
                                            <p class="card-text">Size: {{ pizza_assembly.pizza.size.description }}  </p>
                                            <p class="card-text">Price: {{ pizza_assembly.pizza.price }}  </p>
                                            {% for topping in pizza_assembly.toppings.all %}
                                                <p class="card-text">{{ topping.description}} </p>
                                            {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% for salad in order.salads.all %}
                            <div class="card card-cascade wider">
                                <div class="card-body text-center">
                                    <div class="col-xs-6 col-md-4">
                                        <img src="https://www.cicis.com/media/1235/saladbar_saladmix.png" alt="Card image" class="img-thumbnail">
                                        <p class="card-title"><b>{{ salad.description }}</b> </p>
                                        <p class="card-text">Price: {{ salad.price }}  </p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% for pasta in order.pastas.all %}
                            <div class="card card-cascade wider">
                                <div class="card-body text-center">
                                    <div class="col-xs-6 col-md-4">
                                        <img src="https://www.cicis.com/media/1234/saladbar_pastasalad.png" alt="Card image" class="img-thumbnail">
                                        <p class="card-title"><b>{{ pasta.description }}</b> </p>
                                        <p class="card-text">Price: {{ pasta.price }}  </p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% for plate in order.dinner_plates.all %}
                            <div class="card card-cascade wider">
                                <div class="card-body text-center">
                                    <div class="col-xs-6 col-md-4">
                                        <img src="https://www.cicis.com/media/1250/side_pastamarinara.png" alt="Card image" class="img-thumbnail">
                                        <p class="card-title"><b>{{ plate.type.description }}</b> </p>
                                        <p class="card-text">Price: {{ plate.size.price }}  </p>
                                        <p class="card-text">Price: {{ plate.price }}  </p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <form class="form-horizontal" role="form" action="{% url 'orders:clear_cart'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="form-group">
                                <div class="col-sm-offset-1 col-sm-10 text-center">
                                        <button type="submit" class="btn btn-success">Clear Cart</button>
                                </div>
                            </div>
                            </form>
                    {% endif %}
                </div>
                <div class="panel-footer">
                    <a href="{% url 'orders:index' %}">Back to Menu</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/order_list.html
{% extends 'visitor.html' %}
{% block title %}Orders{% endblock %}
{% block order_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid pizza-container">
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error %}
                        <p><strong>{{ error }}</strong></p>
                    {% endif %}
                    {% if orders %}
                        <table class="table table-bordered sortable">
                            <thead>
                                <tr scope="column">
                                    <th class="col-xs-1" data-field="ID" data-sortable="true">Order Number</th>
                                    <th class="col-xs-1" data-field="Total" data-sortable="true">Order Total</th>
                                    <th class="col-xs-1" data-field="Total" data-sortable="true">Order Items</th>
                                    <th class="col-xs-1" data-field="Status" data-sortable="true">Order Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders%}
                                    <tr id="tr-id-2" class="tr-class-2">
                                        <td>{{ order.id }}</td>
                                        <td>${{ order.total }}</td>
                                        <td>
                                            <ol>
                                                {% for pizza_assembly in order.pizzas_assemblies.all %}
                                                    <li>
                                                        {{ pizza_assembly.pizza.type.description}},
                                                        {{ pizza_assembly.pizza.size.description}},
                                                        {{ pizza_assembly.pizza.option.description}},<br>
                                                        {% for topping in pizza_assembly.toppings.all %}
                                                            <ul>
                                                                <li>{{ topping.description}}</li>
                                                            </ul>
                                                        {% endfor %}
                                                        {% if pizza_assembly.toppings.all|length == 0 %}
                                                            <ul>
                                                                <li>No Toppings</li>
                                                            </ul>
                                                        {% endif %}
                                                    </li>
                                                {% endfor %}
                                                {% for salad in order.salads.all %}
                                                    <li>
                                                        {{ salad.description}}
                                                    </li>
                                                {% endfor %}
                                                {% for pasta in order.pastas.all %}
                                                    <li>
                                                        {{ pasta.description}}
                                                    </li>
                                                {% endfor %}
                                                {% for plate in order.dinner_plates.all %}
                                                    <li>
                                                        {{ plate.type.description}},
                                                        {{ plate.size.description}}
                                                    </li>
                                                {% endfor %}
                                            </ol>
                                        </td>
                                        {% if order.is_complete == True %}
                                            <td>Delivered</td>
                                        {% else %}
                                            <td>In Progress</td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
                <div class="panel-footer">
                    <a href="{% url 'orders:index' %}">Back to Menu</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pizza App</title>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block menu_active %}{% endblock %}"><a href="{% url 'orders:index' %}"><span aria-hidden="true"></span>&nbsp; Menu</a></li>
            </ul>
            {% if not user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="{% block register_active %}{% endblock %}"><a href="{% url 'orders:register' %}">Register</a></li>
                    <li class="{% block login_active %}{% endblock %}"><a href="{% url 'orders:enter' %}">Log In</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav">
                    <li class="{% block cart_active %}{% endblock %}"><a href="{% url 'orders:process_cart' 0 %}"><span aria-hidden="true"></span>&nbsp; Cart</a></li>
                    <li class="{% block order_active %}{% endblock %}"><a href="{% url 'orders:display_orders' %}"><span aria-hidden="true"></span>&nbsp; Orders</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'orders:exit' %}">
                            <span aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>